server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  task:
    scheduling:
      pool:
        size: 4
  security:
    oauth2:
      client:
        uri: http://127.0.0.1:4200
      resourceserver:
        user:
          timeout: 5000
          schedule:
            cron: '0 0 */1 * * *' # частота обновления кэша пользователей
        jwt:
          issuer-uri: http://auth:8082

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://report_db:5433/bank_reports
    username: reporting_sa
    password: sa123
    driver-class-name: org.postgresql.Driver
  accumulator:
    settings:
      activity:
        schedule: '*/15 * * * * *' # частота обновления статистики по операциям - 1 раз в 15 секунд
      statuses:
        schedule: '*/15 * * * * *' # частота обновления статусов операций - 1 раз в 15 секунд
      balancing:
        schedule: '*/15 * * * * *' # частота обновления истории изменения баланса - 1 раз в 15 секунд

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:reporting_tests;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: test_sa
    password: 123
  accumulator:
    settings:
      interval: 10000
      activity:
        schedule: '*/5 * * * * *' # частота обновления статистики по операциям - 1 раз в 5 секунд
      statuses:
        schedule: '*/5 * * * * *' # частота обновления статусов операций - 1 раз в 5 секунд
      balancing:
        schedule: '*/5 * * * * *' # частота обновления истории изменения баланса - 1 раз в 5 секунд